name: Sync to Complete-Linux-Hardening-Kit

on:
  schedule:
    - cron: '0 4,16 * * *'  # Runs at 4 AM and 4 PM UTC daily
  push:
    branches:
      - main  # Also runs immediately when you push
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Apache-Honeypot
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Apache-Honeypot
          token: ${{ secrets.PAT }}
          path: Apache-Honeypot
      
      - name: Sync Apache-Honeypot
        run: |
          find Complete-Linux-Hardening-Kit/Apache-Honeypot/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Apache-Honeypot/

      - name: Checkout Auto-enable-UFW
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Auto-enable-UFW
          token: ${{ secrets.PAT }}
          path: Auto-enable-UFW
      
      - name: Sync Auto-enable-UFW
        run: |
          find Complete-Linux-Hardening-Kit/Auto-enable-UFW/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Auto-enable-UFW/

      - name: Checkout Automated-Server-Backup
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Automated-Server-Backup
          token: ${{ secrets.PAT }}
          path: Automated-Server-Backup
      
      - name: Sync Automated-Server-Backup
        run: |
          find Complete-Linux-Hardening-Kit/Automated-Server-Backup/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Automated-Server-Backup/

      - name: Checkout Comprehensive-Fail2ban-Configuration
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Comprehensive-Fail2ban-Configuration
          token: ${{ secrets.PAT }}
          path: Comprehensive-Fail2ban-Configuration
      
      - name: Sync Comprehensive-Fail2ban-Configuration
        run: |
          find Complete-Linux-Hardening-Kit/Comprehensive-Fail2ban-Configuration/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Comprehensive-Fail2ban-Configuration/

      - name: Checkout Comprehensive-Linux-Server-Hardening-Guide
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Comprehensive-Linux-Server-Hardening-Guide
          token: ${{ secrets.PAT }}
          path: Comprehensive-Linux-Server-Hardening-Guide
      
      - name: Sync Comprehensive-Linux-Server-Hardening-Guide
        run: |
          find Complete-Linux-Hardening-Kit/Comprehensive-Linux-Server-Hardening-Guide/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Comprehensive-Linux-Server-Hardening-Guide/

      - name: Checkout IP-Block
        uses: actions/checkout@v4
        with:
          repository: flaneurette/IP-Block
          token: ${{ secrets.PAT }}
          path: IP-Block
      
      - name: Sync IP-Block
        run: |
          find Complete-Linux-Hardening-Kit/IP-Block/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/IP-Block/

      - name: Checkout Linux-Rat-Scan
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Linux-Rat-Scan
          token: ${{ secrets.PAT }}
          path: Linux-Rat-Scan
      
      - name: Sync Linux-Rat-Scan
        run: |
          find Complete-Linux-Hardening-Kit/Linux-Rat-Scan/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Linux-Rat-Scan/

      - name: Checkout Tailscale-Monitor
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Tailscale-Monitor
          token: ${{ secrets.PAT }}
          path: Tailscale-Monitor
      
      - name: Sync Tailscale-Monitor
        run: |
          find Complete-Linux-Hardening-Kit/Tailscale-Monitor/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Tailscale-Monitor/

      - name: Checkout Verify-USB-Stick
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Verify-USB-Stick
          token: ${{ secrets.PAT }}
          path: Verify-USB-Stick
      
      - name: Sync Verify-USB-Stick
        run: |
          find Complete-Linux-Hardening-Kit/Verify-USB-Stick/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Verify-USB-Stick/

      - name: Checkout PHP-Traffic-Volumizer
        uses: actions/checkout@v4
        with:
          repository: flaneurette/PHP-Traffic-Volumizer
          token: ${{ secrets.PAT }}
          path: PHP-Traffic-Volumizer
      
      - name: Sync PHP-Traffic-Volumizer
        run: |
          find Complete-Linux-Hardening-Kit/PHP-Traffic-Volumizer/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/PHP-Traffic-Volumizer/

      - name: Checkout Tailscale-Split-Traffic-Setup-for-Web-Server
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Tailscale-Split-Traffic-Setup-for-Web-Server
          token: ${{ secrets.PAT }}
          path: Tailscale-Split-Traffic-Setup-for-Web-Server
      
      - name: Sync Tailscale-Split-Traffic-Setup-for-Web-Server
        run: |
          find Complete-Linux-Hardening-Kit/Tailscale-Split-Traffic-Setup-for-Web-Server/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Tailscale-Split-Traffic-Setup-for-Web-Server/

      - name: Checkout VPS-Audit
        uses: actions/checkout@v4
        with:
          repository: flaneurette/VPS-Audit
          token: ${{ secrets.PAT }}
          path: VPS-Audit
      
      - name: Sync VPS-Audit
        run: |
          find Complete-Linux-Hardening-Kit/VPS-Audit/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/VPS-Audit/

      - name: Checkout Hardening-Encryption-on-Linux
        uses: actions/checkout@v4
        with:
          repository: flaneurette/Hardening-Encryption-on-Linux
          token: ${{ secrets.PAT }}
          path: Hardening-Encryption-on-Linux
      
      - name: Sync Hardening-Encryption-on-Linux
        run: |
          find Complete-Linux-Hardening-Kit/Hardening-Encryption-on-Linux/ -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          rsync -av --exclude='.git' --exclude='.github' another-repo/Complete-Linux-Hardening-Kit/Hardening-Encryption-on-Linux/

      - name: Commit and push changes
        run: |
          cd Complete-Linux-Hardening-Kit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync updates from multiple repos - $(date)"
            git push
          fi
